Bicycle.Web/Controllers/AnimalsController.cs
using AutoMapper;
using Bicycle.Web.DAL.Repositories;
using Bicycle.Web.Entities;
using Bicycle.Web.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Bicycle.Web.Controllers
{
    public class AnimalsController : Controller
    {
        private readonly IRepository<Animal> repo;
        public AnimalsController()
        {
            repo = new AnimalRepostory();
        }
        // GET: Animals
        public ActionResult Index(FilterModel search)
        {
            //ApplicationDbContext context = new ApplicationDbContext();

            //List<AnimalVM> model = context.Animals.Select(a =>
            //    new AnimalVM
            //    {
            //        Id=a.Id,
            //        Name=a.Name,
            //        ImageUrl=a.UrlLink
            //    }).ToList();
            IEnumerable<Animal> list;
            if (search.Name!=null)
                list = repo.GetAll(x=>x.Name.Contains(search.Name));
            else
            {
                list = repo.GetAll();
            }
            var mapper =  MyAutoMapperConfig.GetAutoMapper();
            // сопоставление
            var model = mapper.Map<List<AnimalVM>>(list);

            return View(model);
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(AnimalAddVM model)
        {
            if(model.ImageFile==null)
            {
                ModelState.AddModelError("ImageFile", "Оберіть фото для тварини!");
                return View(model);
            }

            var list = repo.GetAll(x => x.Name == model.Name).ToList();
            if (list.Count > 0)
            {
                ModelState.AddModelError("Name", "Тварина з даним ім'ям уже є!");
                return View(model);
            }

            string fileName = Path.GetRandomFileName()+".jpg";
            string serverPath = Server.MapPath("~/Uploading");
            string fileSave = Path.Combine(serverPath, fileName);
            model.ImageFile.SaveAs(fileSave);
            if (ModelState.IsValid)
            {
                
                Animal animal = new Animal
                {
                    Name = model.Name,
                    UrlLink = fileName,
                    CreateDate = DateTime.Now,
                    ModifyDate = DateTime.Now,
                    DeleteDate = DateTime.Now
                };
                repo.Create(animal);
                repo.Save();
                //context.Animals.Add(animal);
                //context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(model);
        }

        [HttpGet]
        public ActionResult Delete(int id)
        {
            repo.Delete(id);
            repo.Save();
            return RedirectToAction("Index");
        }


    }
}

Bicycle.Web/Controllers/CategoryController.cs
using Bicycle.Web.DAL.Repositories;
using Bicycle.Web.Entities;
using Bicycle.Web.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Bicycle.Web.Controllers
{
    public class CategoryController : Controller
    {
        private readonly IRepository<Category> repo;
        public CategoryController()
        {
            repo = new CategoryRepostory();
        }
        // GET: Category
        public ActionResult Index(FilterModel search)
        {
            //ViewBag.Title = "Категорії --";
            IEnumerable<Category> list;
            if (search.Name != null)
                list = repo.GetAll(x => x.Name.Contains(search.Name));
            else
            {
                list = repo.GetAll();
            }
            var mapper = MyAutoMapperConfig.GetAutoMapper();
            // сопоставление
            var model = mapper.Map<List<CategoryVM>>(list);

            return View(model);
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CategoryAddVM model)
        {
            //ModelState.AddModelError("", "Вас взломали :)!");
            //ModelState.AddModelError("", "Ха ха ха!");
            //return View(model);
            if (model.ImageFile == null)
            {
                ModelState.AddModelError("ImageFile", "Оберіть фото для тварини!");
                return View(model);
            }

            var list = repo.GetAll(x => x.Name == model.Name).ToList();
            if (list.Count > 0)
            {
                ModelState.AddModelError("Name", "Тварина з даним ім'ям уже є!");
                return View(model);
            }
            
            if (ModelState.IsValid)
            {
                string fileName = Path.GetRandomFileName() + ".jpg";
                string serverPath = Server.MapPath("~/Uploading");
                string fileSave = Path.Combine(serverPath, fileName);
                model.ImageFile.SaveAs(fileSave);

                Category animal = new Category
                {
                    Name = model.Name,
                    Image = fileName,
                    CreateDate = DateTime.Now,
                    ModifyDate = DateTime.Now,
                    DeleteDate = DateTime.Now
                };
                repo.Create(animal);
                repo.Save();
                //context.Animals.Add(animal);
                //context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(model);
        }
    }
}

Bicycle.Web/Controllers/ShopController.cs
using Bicycle.Web.DAL.Repositories;
using Bicycle.Web.Entities;
using Bicycle.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Bicycle.Web.Controllers
{
    
    public class ShopController : Controller
    {
        private readonly IRepository<Product> _productRepository;
        private readonly IRepository<Category> _categoryRepository;
        public ShopController()
        {
            _productRepository = new ProductRepository();
            _categoryRepository = new CategoryRepostory();
        }
        // GET: Category
        public ActionResult Index(FilterModel search)
        {
            //ViewBag.Title = "Категорії --";
            IEnumerable<Product> list;
            if (search.Name != null)
                list = _productRepository.GetAll(x => x.Name.Contains(search.Name));
            else
            {
                list = _productRepository.GetAll();
            }
            var mapper = MyAutoMapperConfig.GetAutoMapper();
            // сопоставление
            var model = mapper.Map<List<ProductVM>>(list);

            return View(model);
        }

        [HttpGet]
        public ActionResult Create()
        {
            ProductAddVM model = new ProductAddVM();
            var categories = _categoryRepository.GetAll();
            var mapper = MyAutoMapperConfig.GetAutoMapper();
            // сопоставление
            var select = mapper.Map<List<SelectItemVM>>(categories);

            model.SetCategoriesSelect(select);

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ProductAddVM model)
        {
            if (ModelState.IsValid)
            {
                Product animal = new Product()
                {
                    Name = model.Name,
                    Price=model.Price,
                    Quantity=model.Quantity,
                    CategoryId=model.CategoryId,
                    CreateDate = DateTime.Now,
                    ModifyDate = DateTime.Now,
                    DeleteDate = DateTime.Now
                };
                _productRepository.Create(animal);
                _productRepository.Save();
                //context.Animals.Add(animal);
                //context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(model);
        }




        public ActionResult Search()
        {
            return View();
        }
    }
}

Bicycle.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Bicycle.Web/Views/Shared/_MyLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Вело магазин @ViewBag.Title</title>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
</head>
<body>
    <div class="container">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="#">Navbar</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item active">
                        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        @Html.ActionLink("Тварини", "Index", "Animals", null, new { @class = "nav-link" })
                        @*<a class="nav-link" href="\Animals\Index">Тварини</a>*@
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("Index", "Shop")">Магазин</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("Index", "Category")">Категорії</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link disabled" href="#">Disabled</a>
                    </li>
                </ul>
            </div>
        </nav>

        @RenderBody()
    </div>

    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>